# Site settings
title: Joe Mozden
email: jmozden3@gmail.com
description: >-
  Personal website of Joe Mozden
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jmozden3/github.io" # the base hostname & protocol for your site

# Social links
github_username: https://github.com/jmozden3
linkedin_username: https://www.linkedin.com/in/joe-mozden/

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor